name: Test
on: push
jobs:
    docker:
        name: Docker
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.0

            - name: Build
              run: docker build -t monopoly-go-bot .

            - name: Test
              run: docker run monopoly-go-bot
