name: Test
on: push
jobs:
    docker:
        name: Docker
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.0

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version-file: .python-version
                  cache: pip

            - name: Install Dependencies
              run: pip install -r requirements.txt

            - name: Test
              shell: pwsh
              run: |
                  $process = Start-Process -FilePath powershell -ArgumentList start.ps1 -PassThru;
                  $result = $process.WaitForExit(5000);
                  if ($result) {
                      Write-Host "Exited with code $($process.ExitCode)";
                  } else {
                      Stop-Process -Id $process.Id -Force;
                      Write-Host "Successful";
                  }
